if(waffle_has_wayland OR waffle_has_x11_egl OR waffle_has_gbm OR waffle_on_android OR waffle_has_headless_egl)
    set(waffle_has_egl TRUE)
else(waffle_has_wayland OR waffle_has_x11_egl)
    set(waffle_has_egl FALSE)
endif()

if(waffle_has_glx OR waffle_has_x11_egl)
    set(waffle_has_x11 TRUE)
else()
    set(waffle_has_x11 FALSE)
endif()
